#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = (function () use ($app) {
    $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

    return $kernel->handle(
        $input = new ArgvInput,
        new ConsoleOutput
    );
})();

exit($status);
